# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ventanas\Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Loggeo(object):
    def setupUi(self, Loggeo):
        Loggeo.setObjectName("Loggeo")
        Loggeo.resize(364, 176)
        self.centralwidget = QtWidgets.QWidget(Loggeo)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 160, 130))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelUser = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelUser.setObjectName("labelUser")
        self.verticalLayout.addWidget(self.labelUser)
        self.editUser = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.editUser.setObjectName("editUser")
        self.verticalLayout.addWidget(self.editUser)
        self.labelPass = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelPass.setObjectName("labelPass")
        self.verticalLayout.addWidget(self.labelPass)
        self.editPass = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.editPass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.editPass.setObjectName("editPass")
        self.verticalLayout.addWidget(self.editPass)
        self.labelAcceso = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelAcceso.setFont(font)
        self.labelAcceso.setText("")
        self.labelAcceso.setObjectName("labelAcceso")
        self.verticalLayout.addWidget(self.labelAcceso)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(240, 20, 95, 98))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnEnter = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnEnter.setObjectName("btnEnter")
        self.verticalLayout_2.addWidget(self.btnEnter)
        self.btnCrear = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnCrear.setObjectName("btnCrear")
        self.verticalLayout_2.addWidget(self.btnCrear)
        self.btnCancel = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnCancel.setObjectName("btnCancel")
        self.verticalLayout_2.addWidget(self.btnCancel)
        Loggeo.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(Loggeo)
        self.statusBar.setObjectName("statusBar")
        Loggeo.setStatusBar(self.statusBar)

        self.retranslateUi(Loggeo)
        QtCore.QMetaObject.connectSlotsByName(Loggeo)

    def retranslateUi(self, Loggeo):
        _translate = QtCore.QCoreApplication.translate
        Loggeo.setWindowTitle(_translate("Loggeo", "Login"))
        self.labelUser.setText(_translate("Loggeo", "Usuario"))
        self.editUser.setStatusTip(_translate("Loggeo", "Nombre de Usuario"))
        self.labelPass.setText(_translate("Loggeo", "Contraseña"))
        self.editPass.setStatusTip(_translate("Loggeo", "Ingrese su Contraseña"))
        self.btnEnter.setText(_translate("Loggeo", "Entrar"))
        self.btnCrear.setText(_translate("Loggeo", "Crear Usuario"))
        self.btnCancel.setText(_translate("Loggeo", "Cancelar"))
