# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ventanas\MenuCuentas.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CountsWindow(object):
    def setupUi(self, CountsWindow):
        CountsWindow.setObjectName("CountsWindow")
        CountsWindow.resize(300, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CountsWindow.sizePolicy().hasHeightForWidth())
        CountsWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(CountsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tablaCuentas = QtWidgets.QTableWidget(self.centralwidget)
        self.tablaCuentas.setGeometry(QtCore.QRect(10, 10, 230, 450))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tablaCuentas.sizePolicy().hasHeightForWidth())
        self.tablaCuentas.setSizePolicy(sizePolicy)
        self.tablaCuentas.setObjectName("tablaCuentas")
        self.tablaCuentas.setColumnCount(2)
        self.tablaCuentas.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablaCuentas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaCuentas.setHorizontalHeaderItem(1, item)
        CountsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CountsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 26))
        self.menubar.setObjectName("menubar")
        self.menuAcciones = QtWidgets.QMenu(self.menubar)
        self.menuAcciones.setObjectName("menuAcciones")
        CountsWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(CountsWindow)
        self.statusBar.setObjectName("statusBar")
        CountsWindow.setStatusBar(self.statusBar)
        self.actionCrearCuenta = QtWidgets.QAction(CountsWindow)
        self.actionCrearCuenta.setObjectName("actionCrearCuenta")
        self.actionOperar = QtWidgets.QAction(CountsWindow)
        self.actionOperar.setObjectName("actionOperar")
        self.actionDepositar = QtWidgets.QAction(CountsWindow)
        self.actionDepositar.setObjectName("actionDepositar")
        self.menuAcciones.addAction(self.actionCrearCuenta)
        self.menuAcciones.addAction(self.actionOperar)
        self.menuAcciones.addAction(self.actionDepositar)
        self.menubar.addAction(self.menuAcciones.menuAction())

        self.retranslateUi(CountsWindow)
        QtCore.QMetaObject.connectSlotsByName(CountsWindow)

    def retranslateUi(self, CountsWindow):
        _translate = QtCore.QCoreApplication.translate
        CountsWindow.setWindowTitle(_translate("CountsWindow", "MainWindow"))
        item = self.tablaCuentas.horizontalHeaderItem(0)
        item.setText(_translate("CountsWindow", " Moneda"))
        item = self.tablaCuentas.horizontalHeaderItem(1)
        item.setText(_translate("CountsWindow", "Saldo"))
        self.menuAcciones.setTitle(_translate("CountsWindow", "Acciones"))
        self.actionCrearCuenta.setText(_translate("CountsWindow", "Crear Cuenta..."))
        self.actionOperar.setText(_translate("CountsWindow", "Operar..."))
        self.actionDepositar.setText(_translate("CountsWindow", "Depositar..."))
