# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ventanas\TradeDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TradeDialog(object):
    def setupUi(self, TradeDialog):
        TradeDialog.setObjectName("TradeDialog")
        TradeDialog.resize(537, 264)
        self.horizontalLayoutWidget = QtWidgets.QWidget(TradeDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(320, 220, 194, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAccept = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnAccept.setObjectName("btnAccept")
        self.horizontalLayout.addWidget(self.btnAccept)
        self.btnCancel = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.verticalLayoutWidget = QtWidgets.QWidget(TradeDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 514, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(50)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(50)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.orgCrrncy = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.orgCrrncy.setObjectName("orgCrrncy")
        self.horizontalLayout_2.addWidget(self.orgCrrncy)
        self.dstCrrncy = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.dstCrrncy.setObjectName("dstCrrncy")
        self.horizontalLayout_2.addWidget(self.dstCrrncy)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(TradeDialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 119, 160, 131))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.buyerEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.buyerEdit.setObjectName("buyerEdit")
        self.verticalLayout_2.addWidget(self.buyerEdit)
        self.btnComprar = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.btnComprar.setObjectName("btnComprar")
        self.verticalLayout_2.addWidget(self.btnComprar)
        self.btnDebitar = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.btnDebitar.setObjectName("btnDebitar")
        self.verticalLayout_2.addWidget(self.btnDebitar)

        self.retranslateUi(TradeDialog)
        QtCore.QMetaObject.connectSlotsByName(TradeDialog)

    def retranslateUi(self, TradeDialog):
        _translate = QtCore.QCoreApplication.translate
        TradeDialog.setWindowTitle(_translate("TradeDialog", "Operar..."))
        self.btnAccept.setText(_translate("TradeDialog", "Aceptar"))
        self.btnCancel.setText(_translate("TradeDialog", "Cancelar"))
        self.label_2.setText(_translate("TradeDialog", "Cuenta Origen"))
        self.label.setText(_translate("TradeDialog", "Cuenta Destino"))
        self.buyerEdit.setPlaceholderText(_translate("TradeDialog", "Cantidad"))
        self.btnComprar.setText(_translate("TradeDialog", "Cantidad a Comprar"))
        self.btnDebitar.setText(_translate("TradeDialog", "Cantidad a Debitar"))
